### ISSUE TITLE
Desenhar Telas

### ISSUE THREAD

**Issue by jessica-leite** [jessica-leite/chamados-delas#2]
1. Login
2. Cadastro
3. Usuário
4. Técnico
5. Administrador
6. Chamados

**Comment by julooch** [comment]
**Link do canvas das telas:**

https://www.canva.com/design/DAGEMq7LWkc/Dizn2uDyLwRKo8FlbEEA8g/edit?utm_content=DAGEMq7LWkc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
