### ISSUE TITLE
Front - Tela Usuario

### ISSUE THREAD

**Issue by ericajv** [jessica-leite/chamados-delas#26]

**Comment by jessica-leite** [comment]
Centralizar botões editar e excluir cadastro na tela de usuário

**Comment by jessica-leite** [comment]
Exibir somente a data, sem o horário

**Comment by jessica-leite** [comment]
Inserir 0 no dia e no mês se tiver só 1 dígito

**Comment by jessica-leite** [comment]
Buscar chamados por id do usuário
